version: '3.8'

services:
  dextar-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dextar_website
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
